

services:
  web:
    build: .
    command: >
      sh -c "
      echo 'Waiting for PostgreSQL to be ready...' &&
      until pg_isready -h db -p 5432 -U theodosi4_user; do
        echo 'PostgreSQL is unavailable - sleeping'
        sleep 2
      done &&
      echo 'PostgreSQL is up - executing command' &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn Theodosi4.wsgi:application --bind 0.0.0.0:8000 --workers 3 --access-logfile - --error-logfile -
      "
    volumes:
      - .:/app  # Mount τον τρέχοντα φάκελο στο /app του container (για development)
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=theodosi4-production-secret-key-change-this-in-production
      - DEBUG=0
      - DATABASE_URL=postgres://theodosi4_user:theodosi4_password@db:5432/theodosi4_db
      - DB_NAME=theodosi4_db
      - DB_USER=theodosi4_user
      - DB_PASSWORD=theodosi4_password
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=theodosi4_user
      - POSTGRES_PASSWORD=theodosi4_password
      - POSTGRES_DB=theodosi4_db
    ports:
      - "5432:5432"  # Εκθέτουμε την πόρτα για debugging αν χρειάζεται
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume: