# Generated by Django 5.2.3 on 2025-06-11 18:31

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import proipiresia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Τύπος Εκπαιδευτικού"
                    ),
                ),
            ],
            options={
                "verbose_name": "Τύπος Εκπαιδευτικού",
                "verbose_name_plural": "Τύποι Εκπαιδευτικών",
            },
        ),
        migrations.CreateModel(
            name="EmploymentRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Σχέση Εργασίας"
                    ),
                ),
            ],
            options={
                "verbose_name": "Σχέση Εργασίας",
                "verbose_name_plural": "Σχέσεις Εργασίας",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Όνομα Ρόλου"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Περιγραφή"),
                ),
            ],
            options={
                "verbose_name": "Ρόλος",
                "verbose_name_plural": "Ρόλοι",
            },
        ),
        migrations.CreateModel(
            name="SchoolYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Σχολικό Έτος"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Ημερομηνία Έναρξης")),
                ("end_date", models.DateField(verbose_name="Ημερομηνία Λήξης")),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Ενεργό"),
                ),
            ],
            options={
                "verbose_name": "Σχολικό Έτος",
                "verbose_name_plural": "Σχολικά Έτη",
                "ordering": ["-name"],
            },
        ),
        migrations.CreateModel(
            name="ServiceProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Όνομα Φορέα"
                    ),
                ),
            ],
            options={
                "verbose_name": "Φορέας Προϋπηρεσίας",
                "verbose_name_plural": "Φορείς Προϋπηρεσίας",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Specialty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Κωδικός Ειδικότητας"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=255, verbose_name="Περιγραφή Ειδικότητας"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ειδικότητα",
                "verbose_name_plural": "Ειδικότητες",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Όνομα")),
                ("last_name", models.CharField(max_length=100, verbose_name="Επώνυμο")),
                (
                    "father_name",
                    models.CharField(max_length=100, verbose_name="Πατρώνυμο"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Τηλέφωνο"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
            ],
            options={
                "verbose_name": "Εκπαιδευτικός",
                "verbose_name_plural": "Εκπαιδευτικοί",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="PYSEEP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "act_number",
                    models.CharField(max_length=50, verbose_name="Αριθμός Πράξης"),
                ),
                ("date", models.DateField(verbose_name="Ημερομηνία")),
                (
                    "school_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="proipiresia.schoolyear",
                        verbose_name="Σχολικό Έτος",
                    ),
                ),
            ],
            options={
                "verbose_name": "ΠΥΣΕΕΠ",
                "verbose_name_plural": "ΠΥΣΕΕΠ",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Όνομα Υπηρεσίας"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ΚΕΔΑΣΥ", "ΚΕΔΑΣΥ"),
                            ("ΣΔΕΥ", "ΣΔΕΥ"),
                            ("ΣΜΕΑΕ", "ΣΜΕΑΕ"),
                            ("ΑΛΛΟ", "ΑΛΛΟ"),
                        ],
                        max_length=50,
                        verbose_name="Κατηγορία",
                    ),
                ),
                (
                    "prefecture",
                    models.CharField(
                        choices=[
                            ("ΑΙΤΩΛΟΑΚΑΡΝΑΝΙΑ", "ΑΙΤΩΛΟΑΚΑΡΝΑΝΙΑ"),
                            ("ΑΧΑΪΑ", "ΑΧΑΪΑ"),
                            ("ΗΛΕΙΑ", "ΗΛΕΙΑ"),
                        ],
                        max_length=50,
                        verbose_name="Νομός",
                    ),
                ),
            ],
            options={
                "verbose_name": "Υπηρεσία",
                "verbose_name_plural": "Υπηρεσίες",
                "ordering": ["prefecture", "category", "name"],
                "unique_together": {("name", "category", "prefecture")},
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recruitment_phase",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Φάση Πρόσληψης",
                    ),
                ),
                (
                    "submission_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Ημερομηνία Υποβολής Αίτησης",
                    ),
                ),
                (
                    "submission_comments",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Σχόλια Ημερομηνίας Υποβολής",
                    ),
                ),
                (
                    "protocol_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Αρ. Πρωτοκόλλου Αίτησης",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "Νέα αίτηση"),
                            ("PENDING_DOCS", "Σε αναμονή δικαιολογητικών"),
                            ("READY_FOR_PYSEEP", "Έτοιμη για ΠΥΣΕΕΠ"),
                            ("COMPLETED", "Ολοκληρωμένη από ΠΥΣΕΕΠ"),
                        ],
                        default="NEW",
                        max_length=20,
                        verbose_name="Κατάσταση",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Ημερομηνία Δημιουργίας"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Ημερομηνία Ενημέρωσης"
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="Έκδοση"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ενεργή")),
                (
                    "application_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=proipiresia.models.Application.application_file_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            )
                        ],
                        verbose_name="Αρχείο Αίτησης",
                    ),
                ),
                (
                    "employee_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="proipiresia.employeetype",
                        verbose_name="Τύπος Εκπαιδευτικού",
                    ),
                ),
                (
                    "pyseep",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="proipiresia.pyseep",
                        verbose_name="ΠΥΣΕΕΠ που θα υποβληθεί",
                    ),
                ),
                (
                    "school_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="proipiresia.schoolyear",
                        verbose_name="Σχολικό Έτος",
                    ),
                ),
                (
                    "current_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="proipiresia.service",
                        verbose_name="Υπηρεσία Τρέχουσας Τοποθέτησης",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="proipiresia.teacher",
                        verbose_name="Εκπαιδευτικός",
                    ),
                ),
            ],
            options={
                "verbose_name": "Αίτηση",
                "verbose_name_plural": "Αιτήσεις",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TeacherSpecialty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Κύρια Ειδικότητα"),
                ),
                (
                    "specialty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="proipiresia.specialty",
                        verbose_name="Ειδικότητα",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="proipiresia.teacher",
                        verbose_name="Εκπαιδευτικός",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ειδικότητα Εκπαιδευτικού",
                "verbose_name_plural": "Ειδικότητες Εκπαιδευτικών",
            },
        ),
        migrations.AddField(
            model_name="teacher",
            name="specialties",
            field=models.ManyToManyField(
                through="proipiresia.TeacherSpecialty",
                to="proipiresia.specialty",
                verbose_name="Ειδικότητες",
            ),
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to.",
                        related_name="proipiresia_user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="proipiresia.role",
                        verbose_name="Ρόλος",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="proipiresia_user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Χρήστης",
                "verbose_name_plural": "Χρήστες",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="PriorService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "protocol_number",
                    models.CharField(
                        default="ΟΠΣΥΔ",
                        max_length=100,
                        verbose_name="Αρ. Πρωτοκόλλου/Βεβ. Προϋπηρεσίας",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Από")),
                ("end_date", models.DateField(verbose_name="Έως")),
                (
                    "years",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Έτη",
                    ),
                ),
                (
                    "months",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(11),
                        ],
                        verbose_name="Μήνες",
                    ),
                ),
                (
                    "days",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(30),
                        ],
                        verbose_name="Ημέρες",
                    ),
                ),
                (
                    "history",
                    models.TextField(blank=True, null=True, verbose_name="Ιστορικό"),
                ),
                (
                    "verified",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ελέγχθηκε"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Παρατηρήσεις"
                    ),
                ),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Εσωτερικές Σημειώσεις"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Ημερομηνία Δημιουργίας"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Ημερομηνία Ενημέρωσης"
                    ),
                ),
                (
                    "version_id",
                    models.PositiveIntegerField(default=1, verbose_name="ID Έκδοσης"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ενεργή")),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="proipiresia.application",
                        verbose_name="Αίτηση",
                    ),
                ),
                (
                    "employment_relation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="proipiresia.employmentrelation",
                        verbose_name="Σχέση Εργασίας",
                    ),
                ),
                (
                    "service_provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="proipiresia.serviceprovider",
                        verbose_name="Φορέας Προϋπηρεσίας",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_services",
                        to="proipiresia.user",
                        verbose_name="Δημιουργήθηκε από",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_services",
                        to="proipiresia.user",
                        verbose_name="Ενημερώθηκε από",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_services",
                        to="proipiresia.user",
                        verbose_name="Ελέγχθηκε από",
                    ),
                ),
            ],
            options={
                "verbose_name": "Προϋπηρεσία",
                "verbose_name_plural": "Προϋπηρεσίες",
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Δημιουργία"),
                            ("UPDATE", "Ενημέρωση"),
                            ("DELETE", "Διαγραφή"),
                            ("STATUS_CHANGE", "Αλλαγή Κατάστασης"),
                            ("VERIFY", "Επαλήθευση"),
                            ("LOGIN", "Σύνδεση"),
                            ("LOGOUT", "Αποσύνδεση"),
                        ],
                        max_length=20,
                        verbose_name="Ενέργεια",
                    ),
                ),
                (
                    "entity",
                    models.CharField(
                        choices=[
                            ("APPLICATION", "Αίτηση"),
                            ("PRIOR_SERVICE", "Προϋπηρεσία"),
                            ("TEACHER", "Εκπαιδευτικός"),
                            ("USER", "Χρήστης"),
                            ("PYSEEP", "ΠΥΣΕΕΠ"),
                            ("OTHER", "Άλλο"),
                        ],
                        max_length=20,
                        verbose_name="Οντότητα",
                    ),
                ),
                ("entity_id", models.PositiveIntegerField(verbose_name="ID Οντότητας")),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Χρονική Στιγμή"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Διεύθυνση IP"
                    ),
                ),
                (
                    "old_values",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Παλιές Τιμές"
                    ),
                ),
                (
                    "new_values",
                    models.JSONField(blank=True, null=True, verbose_name="Νέες Τιμές"),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        verbose_name="Κλειδί Συνεδρίας",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="proipiresia.user",
                        verbose_name="Χρήστης",
                    ),
                ),
            ],
            options={
                "verbose_name": "Καταγραφή Ενεργειών",
                "verbose_name_plural": "Καταγραφές Ενεργειών",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddField(
            model_name="application",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_applications",
                to="proipiresia.user",
                verbose_name="Δημιουργήθηκε από",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_applications",
                to="proipiresia.user",
                verbose_name="Ενημερώθηκε από",
            ),
        ),
        migrations.AddConstraint(
            model_name="pyseep",
            constraint=models.UniqueConstraint(
                fields=("act_number", "date"), name="unique_pyseep"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="teacherspecialty",
            unique_together={("teacher", "specialty")},
        ),
        migrations.AddConstraint(
            model_name="teacher",
            constraint=models.UniqueConstraint(
                fields=("first_name", "last_name", "father_name"), name="unique_teacher"
            ),
        ),
    ]
