# Generated by Django 5.2.3 on 2025-06-15 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proipiresia', '0003_alter_application_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='priorservice',
            name='reduced_hours',
            field=models.PositiveSmallIntegerField(default=40, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)], verbose_name='Ώρες Μειωμένου/Υποχρεωτικού'),
        ),
        migrations.AlterField(
            model_name='priorservice',
            name='days',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Ημέρες'),
        ),
        migrations.AlterField(
            model_name='priorservice',
            name='months',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Μήνες'),
        ),
        migrations.AlterField(
            model_name='priorservice',
            name='years',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Έτη'),
        ),
    ]
