# Generated by Django 5.2.3 on 2025-06-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proipiresia', '0004_priorservice_reduced_hours_alter_priorservice_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='priorservice',
            name='manual_override',
            field=models.BooleanField(default=False, verbose_name='Χειροκίνητη Παράκαμψη'),
        ),
    ]
